### ISSUE TITLE
Error on 'Create New' project WIP 0.0.4 PC and MAC

### ISSUE THREAD

**Issue by mathiasgmachl** [MeshGeometry/Iogram#2]
[Tue Jan 10 12:11:26 2017] INFO: project path already exists. Attempting to open...
[Tue Jan 10 12:11:26 2017] INFO: Project loaded: C:/Users/hiaz/Documents/
[Tue Jan 10 12:11:26 2017] INFO: could not load graph at path

**Comment by danhambleton** [comment]
Hi Mathias,

It looks like you are pointing the Project Manager to your Documents folder, when it should point to a specific project folder....To create a new project, it should look something like this:

![image](https://cloud.githubusercontent.com/assets/1939589/21893001/3ea657ba-d8a7-11e6-9fde-2c935a88ebf1.png)

And to open an existing, you navigate inside the existing project, like this:

![image](https://cloud.githubusercontent.com/assets/1939589/21893029/59046c64-d8a7-11e6-87cd-0bc3fed2ca8c.png)

It is entirely possible that there is a bug in here somewhere :), but maybe try the above first and let me know if it works.

**Comment by danhambleton** [comment]
To clarify, creating a new iogram project means creating a new folder (i.e. an iogram project is not a single file, rather a collection of files kept inside a project folder. Much like Unity).

**Comment by mathiasgmachl** [comment]
Thanks, I am in.
