### ISSUE TITLE
Not working on my mac?

### ISSUE THREAD

**Issue by yitzilitt** [MeshGeometry/Iogram#4]
![screen shot 2017-05-08 at 10 01 35 pm](https://cloud.githubusercontent.com/assets/28551587/25832713/3fe64790-343a-11e7-8463-694f1dae9163.png)
Yeah.
Is there any way around this?

**Comment by elissa-ross** [comment]
Thank you for this. We are having deployment issues with our Mac build. As you discovered, it presently only runs on 10.12. We are working on it!

**Comment by elissa-ross** [comment]
We have just released a new version of the editor, which is built for 10.11 (and also contains many new features!!). However, we lack a test machine to make sure our build is working. We'd be grateful for your feedback. Thanks for your patience!

**Comment by yitzilitt** [comment]
[Untitled.zip](https://github.com/MeshGeometry/Iogram/files/1122941/Untitled.zip)

**Comment by elissa-ross** [comment]
Well, looks like it is working actually! To see something on screen, try hooking up some polylines to that blend component. Or choose a mesh primitive like the torus or the ellipsoid. 

Thanks for your prompt feedback!
